name: Create Release Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up signing info
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}" > keystore.properties
        echo "${{ secrets.RELEASE_KEYSTORE }}" > keystore.jks.asc
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_ENCRYPTION_KEY }}" --batch keystore.jks.asc > keystore.jks
        rm keystore.jks.asc
        
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build app bundle with Gradle
      run: ./gradlew bundleRelease
          
    - name: set up play store access
      run: |
        echo "${{ secrets.PLAY_STORE_CREDENTIALS }}" > playstore_access.json.txt
        base64 -d playstore_access.json.txt > playstore_access.json
        rm playstore_access.json.txt
        
    - name: setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.2'

    - name: setup Fastlane
      run: bundle install
      
    - name: publish metadata and AAB to Play Store Internal
      run: bundle exec fastlane supply --aab app/build/outputs/bundle/release/app-release.aab --track internal
      
    - name: extract version code and version name
      run: |
        echo "VERSION_NAME="$(grep "versionName" app/build.gradle | awk '{print $2}' | sed 's/"//g') >> $GITHUB_ENV
        echo "VERSION_CODE="$(grep "versionCode" app/build.gradle | awk '{print $2}') >> $GITHUB_ENV
        
    - name: create tag and release on GitHub
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION_CODE }}
        name: ${{ env.VERSION_NAME }}
        body_path: fastlane/metadata/android/en-US/changelogs/${{ env.VERSION_CODE }}.txt


