name: Create Release Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up signing info
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}" > keystore.properties
        echo "${{ secrets.RELEASE_KEYSTORE }}" > keystore.jks.asc
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_ENCRYPTION_KEY }}" --batch keystore.jks.asc > keystore.jks
        rm keystore.jks.asc
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build app bundle with Gradle
      run: ./gradlew bundleRelease
    - name: Build apk with Gradle
      run: ./gradlew assembleRelease
    - uses: actions/upload-artifact@v2
      with:
        name: AAB-APK
        path: |
          app/build/outputs/bundle/release/app-release.aab
          app/build/outputs/apk/release/app-release.apk
